import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/theme";
import fonts from "./fonts";
import { IsLoadingProvider } from "@/context/loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fonts}`}>
      <body>
        <IsLoadingProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </IsLoadingProvider>
      </body>
    </html>
  );
}
